version: 2
jobs:
  build:
    context: Koenighotze
    environment:
      IMAGE_NAME: koenighotze/wordcloud
      RELEASE_TAG: "1.6"
    docker:
      - image: docker:18.06.0-ce

    steps:
      - checkout
      - setup_remote_docker

      - run: docker build -t "${IMAGE_NAME}:${CIRCLE_SHA1}" --build-arg NAME="${IMAGE_NAME}" --build-arg CREATED="n/a" --build-arg TITLE="Wordcloud-cli docker wrappet" --build-arg REVISION="$CIRCLE_SHA1" --build-arg BUILD_URL="$CIRCLE_BUILD_URL" --build-arg SOURCE="$CIRCLE_REPOSITORY_URL" .

      - run: |
         echo $DOCKERHUB_LOGIN_PASSWORD | docker login --username koenighotze --password-stdin
         docker push ${IMAGE_NAME}:${CIRCLE_SHA1}"
         docker push ${IMAGE_NAME}:${RELEASE_TAG}"
